name: Update docker image and helm chart

on:
    pull_request:
        branches:
            - develop



jobs:
    # test:
    #     runs-on: ubuntu-latest

    #     steps:
    #     - name: Checkout code
    #       uses: actions/checkout@v2

    #     - name: Node install
    #       uses: actions/setup-node@v4
    #       with:
    #         node-version: '>= 20.5.0'
        
    #     - name: Npm install
    #       run: npm install

    #     - name: Run Test
    #       run: npm test
        

    docker-image-build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Login to Docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_SECRET }}

        - name: Build Docker image
          run: docker build -t geonhyukseo/goormfront:${{ github.sha }} .

        - name: Push Docker image
          run: docker push geonhyukseo/goormfront:${{ github.sha }}

            